/** Built-in site pages editable from Admin → Pages (SEO + content where applicable). */
const SYSTEM_PAGES = [
  {
    systemKey: "home",
    slug: "home",
    path: "/",
    title: "Home",
    pageKind: "meta-only",
    defaultTitle: "xHub4u - World's Biggest HD Porn Tube",
    defaultDescription:
      "xHub4u is the world's biggest HD porn tube. Browse free adult videos in HD.",
  },
  {
    systemKey: "videos",
    slug: "videos",
    path: "/videos",
    title: "All Videos",
    pageKind: "meta-only",
    defaultTitle: "All Videos",
    defaultDescription: "Browse all videos with filters like recent, most viewed, top rated, and duration.",
  },
  {
    systemKey: "categories",
    slug: "categories",
    path: "/categories",
    title: "Categories",
    pageKind: "meta-only",
    defaultTitle: "Categories",
    defaultDescription: "Browse videos by category on xHub4u.",
  },
  {
    systemKey: "search",
    slug: "search",
    path: "/search",
    title: "Search",
    pageKind: "meta-only",
    defaultTitle: "Search Videos",
    defaultDescription: "Search videos on xHub4u.",
  },
  {
    systemKey: "privacy-policy",
    slug: "privacy-policy",
    path: "/privacy-policy",
    title: "Privacy Policy",
    pageKind: "content",
    defaultTitle: "Privacy Policy",
    defaultDescription:
      "Privacy policy for xHub4u, an adults-only video platform. Learn how we handle your data.",
  },
  {
    systemKey: "terms-and-conditions",
    slug: "terms-and-conditions",
    path: "/terms-and-conditions",
    title: "Terms and Conditions",
    pageKind: "content",
    defaultTitle: "Terms and Conditions",
    defaultDescription:
      "Terms of use for xHub4u, an adults-only video platform with mature and explicit content.",
  },
  {
    systemKey: "cookie-policy",
    slug: "cookie-policy",
    path: "/cookie-policy",
    title: "Cookie Policy",
    pageKind: "content",
    defaultTitle: "Cookie Policy",
    defaultDescription:
      "Cookie policy for xHub4u, including age verification and preferences on our adult platform.",
  },
  {
    systemKey: "report-removal",
    slug: "report-removal",
    path: "/report-removal",
    title: "Video Removal Request",
    pageKind: "content",
    defaultTitle: "Video Removal Request",
    defaultDescription: "Submit a request to remove a video from xHub4u.",
  },
  {
    systemKey: "login",
    slug: "login",
    path: "/auth/login",
    title: "Login",
    pageKind: "meta-only",
    defaultTitle: "Login",
    defaultDescription: "Sign in to your xHub4u account.",
    defaultNoindex: true,
  },
  {
    systemKey: "signup",
    slug: "signup",
    path: "/auth/signup",
    title: "Sign Up",
    pageKind: "meta-only",
    defaultTitle: "Sign Up",
    defaultDescription: "Create your xHub4u account.",
    defaultNoindex: true,
  },
  {
    systemKey: "forgot-password",
    slug: "forgot-password",
    path: "/auth/forgot-password",
    title: "Forgot Password",
    pageKind: "meta-only",
    defaultTitle: "Forgot Password",
    defaultDescription: "Reset your xHub4u account password.",
    defaultNoindex: true,
  },
  {
    systemKey: "reset-password",
    slug: "reset-password",
    path: "/auth/reset-password",
    title: "Reset Password",
    pageKind: "meta-only",
    defaultTitle: "Reset Password",
    defaultDescription: "Choose a new password for your xHub4u account.",
    defaultNoindex: true,
  },
  {
    systemKey: "dashboard",
    slug: "dashboard",
    path: "/dashboard",
    title: "Dashboard",
    pageKind: "meta-only",
    defaultTitle: "Dashboard",
    defaultDescription: "Your xHub4u account dashboard.",
    defaultNoindex: true,
  },
];

module.exports = { SYSTEM_PAGES };
