const dotenv = require("dotenv");
dotenv.config();

const fs = require("fs");
const connectDB = require("../src/config/db");
const Video = require("../src/models/Video");
const StorageServer = require("../src/models/StorageServer");
const {
  extractAndUploadPreviewClipFromVideo,
  extractAndUploadThumbnailFromVideo,
  prepareLocalVideoInputForPreview,
  probeVideo,
} = require("../src/services/videoProcessingService");
const { deleteFileFromR2, extractObjectKeyFromUrl, getDefaultStorageServer } = require("../src/utils/r2Client");

const parseArgs = () => {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const previewOnly = args.includes("--preview-only");
  const thumbnailOnly = args.includes("--thumbnail-only");
  const includeCustomThumbnails = args.includes("--include-custom-thumbnails");
  const limitArg = args.find((arg) => arg.startsWith("--limit="));
  const limit = limitArg ? Number(limitArg.split("=")[1]) : 0;
  const idArg = args.find((arg) => arg.startsWith("--id="));
  const videoId = idArg ? idArg.split("=")[1] : "";

  const regenPreview = !thumbnailOnly;
  const regenThumbnail = !previewOnly;

  return {
    dryRun,
    regenPreview,
    regenThumbnail,
    includeCustomThumbnails,
    limit: Number.isFinite(limit) && limit > 0 ? limit : 0,
    videoId: videoId.trim(),
  };
};

const resolveServerConfig = async (storageServerId) => {
  if (storageServerId) {
    const server = await StorageServer.findById(storageServerId);
    if (server?.isActive) return server.toObject();
  }

  const defaultServer = await getDefaultStorageServer();
  return defaultServer?.isActive ? defaultServer.toObject() : null;
};

const hasHlsSource = (video) => {
  const hasVariant = (video.qualityVariants || []).some(
    (variant) =>
      (typeof variant?.url === "string" && variant.url.includes(".m3u8")) ||
      (typeof variant?.key === "string" && variant.key.endsWith(".m3u8"))
  );
  const hasMaster = typeof video.videoUrl === "string" && video.videoUrl.includes(".m3u8");
  const hasHlsKeys = Array.isArray(video.hlsKeys) && video.hlsKeys.some((key) => String(key).endsWith(".m3u8"));
  return hasVariant || hasMaster || hasHlsKeys;
};

const resolveObjectKey = (storedKey, url) => {
  if (typeof storedKey === "string" && storedKey.trim()) {
    return storedKey.trim();
  }
  return extractObjectKeyFromUrl(url) || "";
};

const isAutoGeneratedThumbnail = (thumbnailKey, thumbnailUrl) => {
  const key = resolveObjectKey(thumbnailKey, thumbnailUrl);
  return Boolean(key && /\/thumbnails\/auto-/i.test(key));
};

const safeDeleteFromR2 = async (objectKey, serverConfig) => {
  if (!objectKey) return;
  try {
    await deleteFileFromR2(objectKey, serverConfig);
  } catch (error) {
    console.warn(`  [warn] Could not delete ${objectKey}: ${error.message}`);
  }
};

const regenerateVideoMedia = async () => {
  const { dryRun, regenPreview, regenThumbnail, includeCustomThumbnails, limit, videoId } = parseArgs();

  if (!regenPreview && !regenThumbnail) {
    console.error("Nothing to do. Remove --preview-only / --thumbnail-only conflict or pass neither.");
    process.exit(1);
  }

  await connectDB();

  let finder = Video.find(videoId ? { _id: videoId } : {}).sort({ createdAt: 1 });
  if (limit > 0) {
    finder = finder.limit(limit);
  }

  const videos = await finder;
  if (!videos.length) {
    console.log("No videos matched the criteria.");
    process.exit(0);
  }

  const tasks = [regenPreview ? "preview" : null, regenThumbnail ? "thumbnail" : null].filter(Boolean).join(" + ");

  console.log(
    `Regenerating ${tasks} for ${videos.length} video(s)` +
      `${dryRun ? " [dry-run]" : ""}` +
      `${includeCustomThumbnails ? " (including custom thumbnails)" : ""}`
  );

  let succeeded = 0;
  let failed = 0;
  let skipped = 0;

  for (const video of videos) {
    const label = `${video._id} — ${video.title}`;

    if (!hasHlsSource(video)) {
      skipped += 1;
      console.log(`[skip] ${label} — no HLS source`);
      continue;
    }

    const previousPreviewKey = resolveObjectKey(video.previewKey, video.previewUrl);
    const previousThumbnailKey = resolveObjectKey(video.thumbnailKey, video.thumbnail);
    const shouldRegenThumbnail =
      regenThumbnail &&
      (includeCustomThumbnails || isAutoGeneratedThumbnail(video.thumbnailKey, video.thumbnail) || !previousThumbnailKey);

    if (regenThumbnail && !shouldRegenThumbnail) {
      console.log(`[skip-thumb] ${label} — custom thumbnail kept (use --include-custom-thumbnails to replace)`);
    }

    if (dryRun) {
      const actions = [];
      if (regenPreview && previousPreviewKey) actions.push(`delete preview ${previousPreviewKey}`);
      if (shouldRegenThumbnail && previousThumbnailKey) actions.push(`delete thumbnail ${previousThumbnailKey}`);
      if (regenPreview) actions.push("generate preview");
      if (shouldRegenThumbnail) actions.push("generate thumbnail");
      console.log(`[dry-run] ${label}: ${actions.join(", ")}`);
      succeeded += 1;
      continue;
    }

    const serverConfig = await resolveServerConfig(video.storageServer);
    if (!serverConfig) {
      skipped += 1;
      console.log(`[skip] ${label} — no active storage server`);
      continue;
    }

    let inputCleanupDir = "";
    const updateFields = {};

    try {
      const localInput = await prepareLocalVideoInputForPreview({ video, serverConfig });
      inputCleanupDir = localInput.cleanupDir;

      let probe = null;
      if (regenPreview || shouldRegenThumbnail) {
        probe = await probeVideo(localInput.localInputPath);
        if (probe.width > 0 && probe.height > 0) {
          updateFields.sourceWidth = probe.width;
          updateFields.sourceHeight = probe.height;
        }
      }

      if (regenPreview) {
        await safeDeleteFromR2(previousPreviewKey, serverConfig);

        const preview = await extractAndUploadPreviewClipFromVideo({
          localInputPath: localInput.localInputPath,
          title: video.title,
          serverConfig,
          durationSeconds: probe?.durationSeconds || video.durationSeconds,
          sourceWidth: probe?.width || video.sourceWidth,
          sourceHeight: probe?.height || video.sourceHeight,
        });

        updateFields.previewUrl = preview.url;
        updateFields.previewKey = preview.key;
      }

      if (shouldRegenThumbnail) {
        await safeDeleteFromR2(previousThumbnailKey, serverConfig);

        const thumbnail = await extractAndUploadThumbnailFromVideo({
          localInputPath: localInput.localInputPath,
          title: video.title,
          serverConfig,
        });

        updateFields.thumbnail = thumbnail.url;
        updateFields.thumbnailKey = thumbnail.key;
      }

      if (Object.keys(updateFields).length) {
        await Video.findByIdAndUpdate(video._id, { $set: updateFields });
      }

      succeeded += 1;
      const done = [];
      if (regenPreview) done.push("preview");
      if (shouldRegenThumbnail) done.push("thumbnail");
      console.log(`[ok] ${label} — ${done.join(" + ")}`);
    } catch (error) {
      failed += 1;
      console.error(`[fail] ${label}: ${error.message}`);
    } finally {
      if (inputCleanupDir) {
        try {
          fs.rmSync(inputCleanupDir, { recursive: true, force: true });
        } catch (_cleanupError) {
          // ignore cleanup failure
        }
      }
    }
  }

  console.log("");
  console.log(`Done. succeeded=${succeeded} failed=${failed} skipped=${skipped} total=${videos.length}`);
  process.exit(failed > 0 ? 1 : 0);
};

regenerateVideoMedia().catch((error) => {
  console.error("Regenerate media script crashed:", error.message);
  process.exit(1);
});
